# Generated by Django 4.2.4 on 2023-11-21 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskAssigned',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.tasklistitems')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.users')),
            ],
        ),
    ]
